### ISSUE TITLE
bug: `FastPriorityQueue` reaches a state where array has length 1 but size: 0

### ISSUE THREAD

**Issue by iiian** [lemire/FastPriorityQueue.js#39]
Unfortunately, I don't have sufficient time to whittle down a reproducible isolated scenario, so I apologize for the poor github issue etiquette. 

I'm trying to use FastPriorityQueue as part of a job queue, (obviously) so that I can pull jobs in priority order. I identified this state of my `FastPriorityQueue` while attempting to troubleshoot a duplicate-job problem. I'm using typescript, so I'm not mucking about _inside of the PQ_ at all. That really makes it feel like this is possibly worth reporting. Again, sorry I don't have better information.

<img width="581" alt="related_to-problems" src="https://github.com/lemire/FastPriorityQueue.js/assets/32170975/ce60cc38-c8a8-435f-ac59-4194a87a30e4">

**Comment by lemire** [comment]
We are always eager for bug reports, and if you encounter a bug when using our public API, we will be glad to investigate.

In this instance, you write that you do not _muck about inside of the PQ at all_, but you explicitly access the internal array which is not part of our public API.

Accessing the internal array is potentially unsafe. Please avoid doing so.

**Comment by iiian** [comment]
Nope, so I *don't* access the internal array in my production code -- the screenshot above is the Javascript REPL in visual studio, so I'm just inspecting the current state of the `FastPriorityQueue` here. This does not represent actual code being called, nor have I tampered with the current state in the REPL, unless `array` is a getter method which has mutating side effects.

In general, I'm only using `.add(), .remove(), .peek(), .poll()`, and of course the `constructor` where I provide my custom comparator function.

I completely understand if you don't feel confident paying much attention to this issue until there's a reproducible subset. If my problem persists and I become convinced it's not a self-induced footgun, I'll invest time into building that. Would you mind keeping the ticket open until then?

**Comment by lemire** [comment]
> Would you mind keeping the ticket open until then?

You should explain what the bug is. You have not presented any evidence whatsoever that there is a bug.

You seem to be concerned that the array size does not match what isEmpty does, but that's not a bug. If it is very much deliberate, we even have a trim function to clear the unused elements:

https://github.com/lemire/FastPriorityQueue.js/blob/9b0b33c5c750a1ed2b863dc1f47f03bd21afee34/FastPriorityQueue.js#L254C1-L257C3

If you think that there is a bug, you should explain how it occurs using solely our public API.

It is very much not a bug that the array is non-empty while the PQ reports that it is empty.

As you admit yourself, it is poor issue etiquette. Please do the necessary work to demonstrate that there is a bug before reporting it.

I am marking this issue as resolved.

You are *very much* encouraged to report and issue. I am eager to read your bug reports... but you must provide a clear explanation of what the bug is... doing otherwise is poor etiquette. Please don't do it.

**Comment by lemire** [comment]
For people reading this, **reaching a state where array has length 1 but size: 0 is not a bug**. 

It is only observable if you access the underlying array, which you should not access.

If one is concerned about this state, one should call the trim function which is there explicitly to free the unused memory.
